module.exports = {
    RESET_STATE: "RESET_STATE",

    ADD_LIST: "ADD_LIST",
    UPDATE_LIST_NAME: "UPDATE_LIST_NAME",
    DELETE_LIST: "DELETE_LIST",
    SET_LIST_TITLE: "SET_LIST_TITLE",
    SET_LIST_COUNT: "SET_LIST_COUNT",

    REFRESH_LISTS: "REFRESH_LISTS",

    ADD_SUBLIST_ITEM: "ADD_SUBLIST_ITEM",
    DELETE_SUBLIST_ITEM: "DELETE_SUBLIST_ITEM",
    SET_ITEM_COMPLETE: "SET_ITEM_COMPLETE",
    SET_SUBLIST_IMPORTANT: "SET_SUBLIST_IMPORTANT",
    SET_SUBLIST_NOTE: "SET_SUBLIST_NOTE",
    SET_SUBLIST_DUE_DATE: "SET_SUBLIST_DUE_DATE",
    SET_SUBLIST_DUE_TIME: "SET_SUBLIST_DUE_TIME",
    SET_SUBLIST_COUNT: "SET_SUBLIST_COUNT",

}