module.exports = {
    ADD_LIST: "ADD_LIST",
    REMOVE_LIST: "REMOVE_LIST",
    SET_LIST_TITLE: "SET_LIST_TITLE",
    SET_LIST_COUNT: "SET_LIST_COUNT",

    REFRESH_LISTS: "REFRESH_LISTS",
    UPDATE_LIST_NAME: "UPDATE_LIST_NAME",
    ADD_SUBLIST_ITEM: "ADD_SUBLIST_ITEM",
    REMOVE_SUBLIST_ITEM: "REMOVE_SUBLIST_ITEM",
    SET_ITEM_COMPLETE: "SET_ITEM_COMPLETE",
    SET_SUBLIST_COUNT: "SET_SUBLIST_COUNT",

}